# Generated by Django 3.1.4 on 2020-12-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201129_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
