# Generated by Django 3.1.2 on 2020-12-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201205_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='VIP',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='demoted',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='deposit',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='warnings',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='demoted',
        ),
        migrations.AddField(
            model_name='users',
            name='VIP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='demoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='users',
            name='warnings',
            field=models.IntegerField(default=0),
        ),
    ]
