# Generated by Django 3.1.2 on 2020-12-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='question',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='survey_idx',
        ),
        migrations.AddField(
            model_name='survey',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
