# Generated by Django 3.1.1 on 2020-11-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Appetizers'), (1, 'Soups & Salads'), (2, 'Bar'), (3, 'House Specials'), (4, 'Beverages'), (5, 'Entrees'), (6, 'Desserts')], default=0)),
                ('itemName', models.CharField(max_length=200)),
                ('itemDescription', models.TextField()),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
    ]
