# Generated by Django 3.1.2 on 2020-12-07 04:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Appetizers'), (1, 'Soups & Salads'), (2, 'Bar'), (3, 'House Specials'), (4, 'Beverages'), (5, 'Entrees'), (6, 'Desserts')], default=0)),
                ('itemName', models.CharField(max_length=200)),
                ('itemDescription', models.TextField()),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemReviews', models.TextField(blank=True, null=True)),
                ('itemImage', models.ImageField(default='default.jpg', upload_to='menu_images')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('orderType', models.SmallIntegerField(choices=[(0, 'Reservation'), (1, 'Pick Up'), (2, 'Delivery')])),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('itemQuantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitems')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
    ]
