# Generated by Django 3.1.3 on 2020-11-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='itemImage',
            field=models.ImageField(default='default.jpg', upload_to='menu_images'),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='itemReviews',
            field=models.TextField(default=''),
        ),
    ]
