# Generated by Django 3.1.2 on 2020-12-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20201206_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='itemKeyword',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
