# Generated by Django 3.1.3 on 2020-11-29 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201114_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orderType', models.SmallIntegerField(choices=[(0, 'Reservation'), (1, 'Pick Up'), (2, 'Delivery')])),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('itemQuantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitems')),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
    ]
