# Generated by Django 3.1.4 on 2020-12-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menuitems_itemkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderType',
            field=models.SmallIntegerField(choices=[(-1, 'Unknown'), (0, 'Reservation'), (1, 'Pick Up'), (2, 'Delivery')], default=-1),
        ),
    ]
