# Generated by Django 3.1.2 on 2020-12-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20201114_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='reviewStar',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
