# Generated by Django 3.1.4 on 2020-12-10 22:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressID', models.IntegerField()),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('zipCode', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Appetizers'), (1, 'Soups & Salads'), (2, 'Bar'), (3, 'House Specials'), (4, 'Beverages'), (5, 'Entrees'), (6, 'Desserts')], default=0)),
                ('itemName', models.CharField(max_length=200)),
                ('itemDescription', models.TextField()),
                ('itemPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemReviews', models.IntegerField()),
                ('Reciews', models.DecimalField(decimal_places=2, max_digits=3, verbose_name=range(0, 5))),
                ('itemImage', models.ImageField(default='default.jpg', upload_to='menu_images')),
                ('itemKeyword', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tableID', models.AutoField(primary_key=True, serialize=False)),
                ('seats', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('tableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('orderDetailID', models.AutoField(primary_key=True, serialize=False)),
                ('itemQuantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('itemID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.menuitems')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordered', models.BooleanField(default=False)),
                ('orderType', models.SmallIntegerField(choices=[(-1, 'Unknown'), (0, 'Reservation'), (1, 'Pick Up'), (2, 'Delivery')], default=-1)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.address')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
